ROLE_MEMBER = 'member'
ROLE_ADMIN = 'admin'
ROLE_MANAGER = 'manager'
ROLE_CHOICES = (
    (ROLE_MANAGER, 'Manager'),
    (ROLE_MEMBER, 'Member'),
)
PENDING = 'PENDING'
STATUS_IN_PROGRESS = 'IN_PROGRESS'
STATUS_DONE = 'DONE'
EXPIRED='EXPIRED'

STATUS_CHOICES = (
    (PENDING, 'PENDING'),
    (STATUS_IN_PROGRESS, 'IN_PROGRESS'),
    (STATUS_DONE, 'DONE'),
    (EXPIRED,'EXPIRED')
)